import Head from 'next/head'
import Navigation from "@/components/staticComponents/Navigation";
import Footer from "@/components/staticComponents/Footer";

export default function Layout({children}) {
  return (
    <>
      <Head>
        <title>Liefertobi Dein Lieferservice</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation />
        <div className='container background-change'>
            {children}
        </div>
      <Footer />
    </>
  )
}
